/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import dao.CandidatosDAO;
import dao.VotantesDAO;
import dao.VotosDAO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Candidatos;
import model.Votantes;
import model.Votos;

/**
 *
 * @author lw005973
 */
public class EleicaoForm extends javax.swing.JFrame {

    /**
     * Creates new form EleicaoForm
     */
    public EleicaoForm() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            CandidatosDAO candidatosDAO = new CandidatosDAO();
            votosDAO = new VotosDAO();
            votantesDAO = new VotantesDAO();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        partido = new javax.swing.JTextField();
        confirma = new javax.swing.JButton();
        branco = new javax.swing.JButton();
        corrige = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("ELEIÇÕES PRESIDENCIAIS - 2018");

        jLabel2.setText("Informe o Número do Candidato:");

        numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroFocusLost(evt);
            }
        });

        jLabel3.setText("Nome do Candidato:");

        nome.setEnabled(false);

        jLabel4.setText("Partido do Candidato:");

        partido.setEnabled(false);

        confirma.setText("CONFIRMA");
        confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaActionPerformed(evt);
            }
        });

        branco.setText("BRANCO");
        branco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brancoActionPerformed(evt);
            }
        });

        corrige.setText("CORRIGE");
        corrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(branco)
                                .addGap(37, 37, 37)
                                .addComponent(corrige)
                                .addGap(30, 30, 30)
                                .addComponent(confirma))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(partido, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(partido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirma)
                    .addComponent(branco)
                    .addComponent(corrige))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroFocusLost
        try {
            CandidatosDAO candidatosDao = new CandidatosDAO();
            
            ArrayList<Candidatos> candidatos = (ArrayList<Candidatos>) candidatosDao.findAll();
        if (numero.getText().isEmpty()){
            numero.setText("");
            partido.setText("");
            nome.setText("");
        }
        int nmr = 99;
        try{
            nmr = Integer.parseInt(numero.getText());
        } catch(Exception ex){
        }
        for (Candidatos candidats : candidatos) {
            if (candidats.getNumCandidato() == (nmr)) {
                candidats = votosDAO.getByNum(nmr);
                if(nmr != 99 && nmr != 0){
                    nome.setText(candidats.getNomeCandidato());
                    partido.setText("" + candidats.getcPartido().getNumPartido());
                } else{
                    nome.setText("");
                    partido.setText("");
                }
                break;
            }
            else {
                partido.setText("");
                nome.setText("");
            }
        }
        } catch (Exception ex) {
            Logger.getLogger(EleicaoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_numeroFocusLost

    private void confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaActionPerformed
        Votantes votantes = new Votantes();
        Candidatos candidatos = new Candidatos();
       
        if(numero.getText().isEmpty()){
            numero.setText(""+99);
            partido.setText(""+99);
            nome.setText("NULO");
        } else if(!votosDAO.validaCodigo(Integer.parseInt(numero.getText()))){
            numero.setText(""+99);
            partido.setText(""+99);
            nome.setText("NULO");
        }
         candidatos = votosDAO.verificaCodigo(Integer.parseInt(numero.getText()));
        try {
            votantes = votantesDAO.findById(celeitor);
        } catch (Exception ex) {
            Logger.getLogger(EleicaoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        votosDAO.save(candidatos, votantes);
        JOptionPane.showMessageDialog(null, "Voto realizado com sucesso!", "Aviso", JOptionPane.WARNING_MESSAGE);
        System.exit(0);
        
    }//GEN-LAST:event_confirmaActionPerformed

    private void brancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brancoActionPerformed
        Votantes votantes = new Votantes();
        Candidatos candidatos = new Candidatos();

        if(numero.getText().isEmpty()){
            numero.setText(""+0);
            partido.setText(""+0);
            nome.setText("BRANCO");
        }
        
        candidatos = votosDAO.verificaCodigo(Integer.parseInt(numero.getText()));
        try {
            votantes = votantesDAO.findById(celeitor);
        } catch (Exception ex) {
            Logger.getLogger(EleicaoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        votosDAO.saveBranco(votantes);

        
        JOptionPane.showMessageDialog(null, "Voto realizado com sucesso!", "Aviso", JOptionPane.WARNING_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_brancoActionPerformed

    private void corrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigeActionPerformed
        numero.setText("");
        partido.setText("");
        nome.setText("");
    }//GEN-LAST:event_corrigeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        this.setVisible(false);
//        LoginDialog login = new LoginDialog(this, true);
//        login.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EleicaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EleicaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EleicaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EleicaoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EleicaoForm().setVisible(true);
            }
        });
    }

    private int celeitor;

    public void setCeleitor(int numero) {
        this.celeitor = numero;
    }
    
    private VotosDAO votosDAO;
    private VotantesDAO votantesDAO;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton branco;
    private javax.swing.JButton confirma;
    private javax.swing.JButton corrige;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField partido;
    // End of variables declaration//GEN-END:variables
}
